In [2]:
import pandas as pd
df1 = pd.read_fwf('data/data_doctor_truthful.txt', header=None)


In [3]:
import pandas as pd

from sklearn.model_selection import train_test_split
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.feature_extraction.text import HashingVectorizer
import itertools
import numpy as np

In [4]:
import matplotlib.pyplot as plt
import numpy as np

from keras import backend as K
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Embedding, Input, RepeatVector
from keras.optimizers import SGD
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import scikitplot.plotters as skplt

In [5]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import scikitplot.plotters as skplt
import pickle
import os.path
from sklearn.svm import SVC

In [6]:
df1.head()

0    1    2    3    4    5  \
0  Dr. Aboolian and his staff went above and beyo...  NaN  NaN  NaN  NaN  NaN   
1  We moved from California and landed in Calgary...  NaN  NaN  NaN  NaN  NaN   
2  Can't really add anything new to what's alread...  NaN  NaN  NaN  NaN  NaN   
3  Dr. Greyvenstein is awesome.  He delivered our...  NaN  NaN  NaN  NaN  NaN   
4  He is so awsome!! I was by chance I found him ...  NaN  NaN  NaN  NaN  NaN   

     6  
0  NaN  
1  NaN  
2  NaN  
3  NaN  
4  NaN

In [7]:
print(df1[0])
df1[1]=1
print(df1)

0      Dr. Aboolian and his staff went above and beyo...
1      We moved from California and landed in Calgary...
2      Can't really add anything new to what's alread...
3      Dr. Greyvenstein is awesome.  He delivered our...
4      He is so awsome!! I was by chance I found him ...
                             ...                        
195    Dr. Greyvenstein is by far the best physician ...
196    Dr. Greyvenstein is an amazing Dr. He is not o...
197    I have been going to Dr. G for the past 2.5yrs...
198    Dr.Greyvenstein just delivered our third child...
199    I LOVE Dr G. After moving to Clagary and findi...
Name: 0, Length: 200, dtype: object
                                                     0  1    2    3    4    5  \
0    Dr. Aboolian and his staff went above and beyo...  1  NaN  NaN  NaN  NaN   
1    We moved from California and landed in Calgary...  1  NaN  NaN  NaN  NaN   
2    Can't really add anything new to what's alread...  1  NaN  NaN  NaN  NaN   
3    Dr. Grey

In [8]:
df2= pd.read_fwf('data/data_doctor_deceptive.txt', header=None)
df2[1]=0
print(df2)

                                                    0   1    2    3    4   \
0    Doctor Aboolian is a board-certified plastic s...   0  NaN  NaN  NaN   
1    I'll be honest, when I was first looking for d...   0  NaN  NaN  NaN   
2    My name is Samantha. I needed to get laser hai...   0  NaN  NaN  NaN   
3    I recently visited with Dr. Fernando Luna for ...   0  NaN  NaN  NaN   
4    Dr. Fernando Luna cares about and listens to m...   0  NaN  NaN  NaN   
..                                                 ...  ..  ...  ...  ...   
351  Dr Greyvenstein was able to see me as a same d...   0  NaN  NaN  NaN   
352  After going through a series of health related...   0  NaN  NaN  NaN   
353  Doctor Ernst Greyvenstein is an amazing physic...   0  NaN  NaN  NaN   
354  Dr.Greyvenstein's practice is at Circle Medica...   0  NaN  NaN  NaN   
355  After having twins, my varicose veins were rea...   0  NaN  NaN  NaN   

      5    6    7    8    9   ...   84   85   86   87   88   89   90   91  

In [9]:
frames = [df1, df2]

df = pd.concat(frames)


In [10]:
df.drop(df.iloc[:, 2:94], inplace = True, axis = 1) 

In [11]:
print(df)
y=df[1]
print(y)

                                                     0  1
0    Dr. Aboolian and his staff went above and beyo...  1
1    We moved from California and landed in Calgary...  1
2    Can't really add anything new to what's alread...  1
3    Dr. Greyvenstein is awesome.  He delivered our...  1
4    He is so awsome!! I was by chance I found him ...  1
..                                                 ... ..
351  Dr Greyvenstein was able to see me as a same d...  0
352  After going through a series of health related...  0
353  Doctor Ernst Greyvenstein is an amazing physic...  0
354  Dr.Greyvenstein's practice is at Circle Medica...  0
355  After having twins, my varicose veins were rea...  0

[556 rows x 2 columns]
0      1
1      1
2      1
3      1
4      1
      ..
351    0
352    0
353    0
354    0
355    0
Name: 1, Length: 556, dtype: int64


In [12]:
X_train, X_test, y_train, y_test = train_test_split(df[0], y, test_size=0.33)

In [13]:
# Initialize the `count_vectorizer` 
count_vectorizer = CountVectorizer(stop_words='english')

# Fit and transform the training data 
count_train = count_vectorizer.fit_transform(X_train)                  # Learn the vocabulary dictionary and return term-document matrix.

# Transform the test set 
count_test = count_vectorizer.transform(X_test)

# Initialize the `tfidf_vectorizer` 
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)    # This removes words which appear in more than 70% of the articles

# Fit and transform the training data 
tfidf_train = tfidf_vectorizer.fit_transform(X_train) 

# Transform the test set 
tfidf_test = tfidf_vectorizer.transform(X_test)

# Get the feature names of `tfidf_vectorizer` 
#print(tfidf_vectorizer.get_feature_names()[-10:])

# Get the feature names of `count_vectorizer` 
#print(count_vectorizer.get_feature_names()[:10])

count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())

tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())

difference = set(count_df.columns) - set(tfidf_df.columns)

print(difference)

# Check whether the DataFrames are equal
print(count_df.equals(tfidf_df))

print(count_df.head())

print(tfidf_df.head())

{'dr'}
False
   00am  00pm  10  100  101  11  12  14  15  150  ...  years  yelling  yes  \
0     0     0   0    0    0   0   0   0   0    0  ...      0        0    0   
1     0     0   0    0    0   0   0   0   0    0  ...      1        0    0   
2     0     0   0    0    0   0   0   0   0    0  ...      0        0    0   
3     0     0   0    0    0   0   0   0   0    0  ...      0        0    0   
4     0     0   0    0    0   0   0   0   0    0  ...      0        0    0   

   young  younger  youngest  youth  youthful  yrs  zero  
0      0        0         0      0         0    0     0  
1      0        0         0      0         0    0     0  
2      0        0         0      0         0    0     0  
3      0        0         0      0         0    0     0  
4      0        0         0      0         0    0     0  

[5 rows x 2960 columns]
   00am  00pm   10  100  101   11   12   14   15  150  ...     years  yelling  \
0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.00

In [14]:
clf = MultinomialNB() 

clf.fit(tfidf_train, y_train)                       # Fit Naive Bayes classifier according to X, y

pred = clf.predict(tfidf_test)                     # Perform classification on an array of test vectors X.
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

print(cm)

accuracy:   0.625
[[114   0]
 [ 69   1]]


In [18]:
clf.fit(count_train, y_train)

pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = confusion_matrix(y_test, pred)
print(cm)

accuracy:   0.832
[[112   2]
 [ 29  41]]


In [19]:
linear_clf = PassiveAggressiveClassifier()

linear_clf.fit(tfidf_train, y_train)
pred = linear_clf.predict(tfidf_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

print(cm)


accuracy:   0.859
[[109   5]
 [ 21  49]]


In [19]:
def baseline_model():
    '''Neural network with 3 hidden layers'''
    model = Sequential()
    model.add(Dense(256, input_dim=300, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.3))
    model.add(Dense(256, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.5))
    model.add(Dense(80, activation='relu', kernel_initializer='normal'))
    model.add(Dense(2, activation="softmax", kernel_initializer='normal'))

    # gradient descent
    sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
    
    # configure the learning process of the model
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

In [20]:
# Get the training and testing data from getEmbeddings
train_data, eval_data, train_labels, eval_labels = X_train, X_test, y_train, y_test
train_labels = train_labels.reshape((-1, 1)).astype(np.int32)
eval_labels = eval_labels.reshape((-1, 1)).astype(np.int32)
   # Create the Estimator
classifier = \
        tf.estimator.Estimator(model_fn=model_fn, model_dir=tensorflow_tmp)

    # Setup logging hook for prediction
tf.logging.set_verbosity(tf.logging.INFO)
tensors_to_log = {"probabilities": "softmax_tensor"}
logging_hook = tf.train.LoggingTensorHook(
    tensors=tensors_to_log, every_n_iter=200)
    
    # Train the model
train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": train_data},
        y=train_labels,
        batch_size=50,
        num_epochs=None,
        shuffle=True)
classifier.train(
        input_fn=train_input_fn,
        steps=TRAIN_STEP,
        hooks=[logging_hook])
    
    # Evaluate the model and print results
eval_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": eval_data},
        y=eval_labels,
        num_epochs=1,
        shuffle=False)
eval_results = classifier.evaluate(input_fn=eval_input_fn)
print(eval_results)   # 81.42%
    
    # Draw the confusion matrix
predict_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": eval_data},
        num_epochs=1,
        shuffle=False)
predict_results = classifier.predict(input_fn=predict_input_fn)
predict_labels = [label["classes"] for label in predict_results]
plot_cmat(eval_labels, predict_labels)


AttributeError: 'Series' object has no attribute 'reshape'

In [23]:
xtr,xte,ytr,yte = X_train, X_test, y_train, y_test
clf = SVC()
clf.fit(xtr, ytr)
y_pred = clf.predict(xte)
m = yte.shape[0]
n = (yte != y_pred).sum()
print("Accuracy = " + format((m-n)/m*100, '.2f') + "%")   # 88.42%

plot_cmat(yte, y_pred)

ValueError: could not convert string to float: 'I am pleased to recommend Dr. Howard Silverman, following my successful breast enhancement surgery he performed on me. While I was somewhat nervous at the outset, Dr. Silverman provided me all the information I needed to make an informed decision to have the surgery. He explained all the procedures thoroughly beforehand, and did the surgery exactly as I requested. He continued with follow-up after the surgery in a most professional manner. I am very happy with the results, and will use Dr. Silverman for any other plastic surgery I may decide to have in the future.'